
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=300000

#stage
spring.datasource.url=jdbc:postgresql://192.168.1.17:5432/crm_stage?currentSchema=crm
spring.datasource.username=crm_stage
spring.datasource.password=crm_stage@123


spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.generate-ddl=true

spring.application.name=utility
eureka.client.serviceUrl.defaultZone=http://192.168.1.17:8090/eureka
eureka.server.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0


keycloak.realm = Laboratory
keycloak.auth-server-url = http://192.168.1.17:8080/
keycloak.ssl-required = external
#keycloak resource is the client ID
keycloak.resource = Reports-management
keycloak.use-resource-role-mappings = false
#The line below will prevent redirect to login page
keycloak.bearer-only: true
server.connection-timeout=6000


server.port=8030

logging.level.org.springframework.jdbc.core = DEBUG

spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=true

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/spring

spring-show-url=192.168.1.17
spring-email-and-file-upload=http://192.168.1.17:8020/uploadFile
spring-email-url=http://192.168.1.17:8020/scheduleEmail

#Email Template Details
emailTemplateTemporary=33
emailTemplate=34

updateUserEmailTemplate=65



#/home/ubuntu/Logs/utility
logging.file.path=/home/avisyscrm2/logs/utility
logging.file.name=${logging.file.path}/utility-service.log
logging.logback.rollingpolicy.file-name-pattern=utility-service-%d{yyyy-MM-dd}.%i.log