#SQL
#PostgreSQL configurations

#Local
#spring.primary.datasource.url=jdbc:postgresql://localhost:5432/crm_dev?currentSchema=crm
#spring.primary.datasource.username=crm_dev
#spring.primary.datasource.password=crm_dev@123

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=300000

#Dev
spring.datasource.url=jdbc:postgresql://localhost:5432/resumebuilder?currentSchema=crm_kwa
spring.datasource.username=resumebuilder
spring.datasource.password=resumebuilder@12345

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml


#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.generate-ddl=true

spring.application.name=utility
eureka.client.serviceUrl.defaultZone=http://localhost:6050/eureka
#eureka.client.serviceUrl.defaultZone=http://localhost:8090/eureka
eureka.server.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0

#keycloak.realm = Laboratory
#keycloak.auth-server-url = http://192.168.1.11:8080/auth/
#keycloak.ssl-required = external
##keycloak resource is the client ID
#keycloak.resource = Reports-management
#keycloak.use-resource-role-mappings = false
##The line below will prevent redirect to login page
#keycloak.bearer-only: true
#server.connection-timeout=6000

server.port=6054

logging.level.org.springframework.jdbc.core = DEBUG

spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=true

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/spring

#spring-email-and-file-upload=http://localhost:8020/uploadFile
#spring-email-url=http://localhost:8020/scheduleEmail

#Email Template Details
emailTemplateTemporary=33
emailTemplate=34

updateUserEmailTemplate=65



#/home/ubuntu/Logs/utility
#logging.file.path=/home/ubuntu/kwa project/utility-service/DEV/log
#logging.file.name=${logging.file.path}/utility-service.log
#logging.logback.rollingpolicy.file-name-pattern=utility-service-%d{yyyy-MM-dd}.%i.log