server.port=${AUTH_PORT}
server.servlet.context-path=/auth-service
spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=uam
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka