server.servlet.context-path=/cv
server.port=${JAVA_CV_PORT}
spring.application.name=java-cv
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=jasper_cv
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=200MB