server.servlet.context-path=/cv
spring.application.name=java-cv
server.port=6056


#DEV
#spring.datasource.url=jdbc:postgresql://192.168.1.11:5432/crm_dev?currentSchema=jasper_cv
#spring.datasource.username=crm_dev
#spring.datasource.password=crm_dev@123
#spring.jpa.show-sql=true

#PROD
spring.datasource.url=jdbc:postgresql://localhost:5432/resumebuilder?currentSchema=jasper_cv
spring.datasource.username=resumebuilder
spring.datasource.password=resumebuilder@12345
spring.jpa.show-sql=false

#Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=jasper_cv
#spring.datasource.username=postgres
#spring.datasource.password=root

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#admin=akshay.deshmukh@avisys.in
#adminPassord=Admin@12345

#admin=aniket.vaishampayan@gmail.com
#adminPassord=Aniket@12345

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


eureka.client.service-url.defaultZone=http://localhost:6050//eureka
#eureka.client.service-url.defaultZone=http://192.168.1.13:6050//eureka

#cv.file-server.url=http://localhost:6055/email/uploadFile

spring.servlet.multipart.max-file-size=200MB