server.servlet.context-path=/uam-service
server.port=6053
spring.application.name=uam-service


#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:6050//eureka


##DEV
#spring.datasource.url=jdbc:postgresql://192.168.1.11:5432/crm_dev?currentSchema=uam
#spring.datasource.username=crm_dev
#spring.datasource.password=crm_dev@123

spring.datasource.url=jdbc:postgresql://localhost:5432/resumebuilder?currentSchema=uam
spring.datasource.username=resumebuilder
spring.datasource.password=resumebuilder@12345
spring.jpa.show-sql=false

#local
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=uam
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.show-sql=true



## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.format_sql=true



# Reset Password token time in minutes diff
#resetPasswordTokenMiniDiff=10
# Reset Password token URL
#resetPasswordTokenUrl = http://localhost:9999/auth/reset-password-token?key=


##Spring Cloud Gateway; Spring MVC found on classpath, which is incompatible with Spring Cloud Gateway Issue
#spring.main.web-application-type=reactive
##The bean 'requestDataValueProcessor', defined in class path resource [org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebMvcSecurityConfiguration.class] and overriding is disabled.
#spring.main.allow-bean-definition-overriding=true
#


#spring.cloud.gateway.routes={id=keycloak, uri=lb://KEYCLOAK, predicates=[Path=/auth/**]}, {id=number-management, uri=lb://NUMBER-MANAGEMENT, predicates=[Path=/number-management/**]}, {id=product-management, uri=lb://PRODUCT-MANAGEMENT, predicates=[Path=/product-management/**]}, {id=rule-management, uri=lb://RULE-MANAGEMENT, predicates=[Path=/rule-management/**]}, {id=service-request, uri=lb://SERVICE-REQUEST, predicates=[Path=/service-management/**]}, {id=utility, uri=lb://UTILITY, predicates=[Path=/utility/**]}, {id=email-service, uri=lb://EMAIL-SERVICE, predicates=[Path=/email/**]}, {id=customer-service, uri=lb://CUSTOMER-SERVICE, predicates=[Path=/customer-management/**]}
#spring.cloud.gateway.routes[0].id=api-gateway
#spring.cloud.gateway.routes[0].uri=lb://API-GATEWAY
#spring.cloud.gateway.routes[0].predicates[0].name=Path
#spring.cloud.gateway.routes[0].predicates[0].args.pattern=/api-gateway/**
#
##spring.cloud.gateway.routes[0].filters[0]=JwtAuth=token,false
#spring.cloud.gateway.default-filters=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#
#
#
#
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
#
#
#
#
