
server.port=6055

# Spring DATASOURCE - local
#spring.datasource.url=jdbc:postgresql://localhost:5432/crm-local?currentSchema=email
#spring.datasource.username=postgres
#spring.datasource.password=root
#DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/resumebuilder?currentSchema=email
spring.datasource.username=resumebuilder
spring.datasource.password=resumebuilder@12345

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.jta.atomikos.datasource.max-pool-size=15

spring.main.allow-bean-definition-overriding=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default-schema=email

## QuartzProperties
spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

## MailProperties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=avisysresumebuilder@gmail.com
#spring.mail.password=tfndzjisgvisodim
spring.mail.username=aniketvaishampayan9111996@gmail.com
spring.mail.password=luzkbaswzlifmdha


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#use for upload file and download file
#app-url=https://www.api.buildresume.co.in:6051/email

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
#spring.servlet.multipart.file-size-threshold=5MB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
#DEV
#file.uploadDir=/home/ubuntu/kwa_project/file-server
#Local
#file.uploadDir=C:\CRM_email_service\17-april


spring.application.name=email-service

#eureka.client.serviceUrl.defaultZone=http://192.168.1.16:8090/eureka
eureka.client.serviceUrl.defaultZone=http://localhost:6050/eureka
eureka.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0


#logging.file.path=/var/log/spring-service
#logging.file.path=/home/avisyscrm/Logs/email-service
#logging.file.name=${logging.file.path}/email-service.log
#logging.logback.rollingpolicy.file-name-pattern=email-service-%d{yyyy-MM-dd}.%i.log



#spring-email-and-file-upload=http://localhost:8020/uploadFile
#spring-email-url=http://localhost:8020/scheduleEmail