server.port=6055
spring.datasource.url=jdbc:postgresql://localhost:5432/resumebuilder?currentSchema=email
spring.datasource.username=resumebuilder
spring.datasource.password=resumebuilder@12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jta.atomikos.datasource.max-pool-size=15
spring.main.allow-bean-definition-overriding=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default-schema=email
spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aniketvaishampayan9111996@gmail.com
spring.mail.password=luzkbaswzlifmdha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app-url=https://localhost:6051/email
spring.servlet.multipart.enabled=true
#spring.servlet.multipart.file-size-threshold=5MB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
file.uploadDir=/home/aniketvaishampayan1998/Spring-Resume-Builder-Project/kwa_project/file-server

spring.application.name=EMAIL_SERVICE
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0

logging.file.path=/home/aniketvaishampayan1998/Spring-Resume-Builder-Project/Logs/email-service
logging.file.name=${logging.file.path}/email-service.log
logging.logback.rollingpolicy.file-name-pattern=email-service-%d{yyyy-MM-dd}.%i.log

spring-email-and-file-upload=http://localhost:8020/uploadFile
spring-email-url=http://localhost:8020/scheduleEmail