
spring.profiles.active=prod

server.servlet.context-path=/email

email.paging-data= select * from email_job_data where job_name ilike '%

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.url=jdbc:postgresql://114.143.224.42:5432/crm_dev?currentSchema=email
#
#spring.datasource.username=crm_dev
#spring.datasource.password=crm_dev@123
#spring.jta.atomikos.datasource.max-pool-size=15
#
#
### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
##spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.PostgreSQL94Dialect
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.default-schema=email
#
##logging.level.org.springframework.jdbc.core = TRACE
#
### QuartzProperties
##quartz
##org.quartz.scheduler.misfirePolicy =  doNothing
#spring.quartz.job-store-type=jdbc
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#
### MailProperties
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=avisyscrm@gmail.com
#spring.mail.password=Crm@12345
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#
#server.port=8020
#
### MULTIPART (MultipartProperties)
## Enable multipart uploads
#spring.servlet.multipart.enabled=true
## Threshold after which files are written to disk.
##spring.servlet.multipart.file-size-threshold=5MB
## Max file size.
#spring.servlet.multipart.max-file-size=200MB
## Max Request Size
#spring.servlet.multipart.max-request-size=215MB
#
### File Storage Properties
## All files uploaded through the REST API will be stored in this directory
##file.uploadDir=C:/Users/Ajay Shinde/Documents/New uploaded files
#file.uploadDir=C:/Users/Public/Documents/File Upload/Development