server.port=${EMAIL_PORT}
spring.application.name=EMAIL_SERVICE
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=email_test
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jta.atomikos.datasource.max-pool-size=15
spring.main.allow-bean-definition-overriding=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default-schema=email
spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
eureka.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0
logging.file.path=/home/aniketvaishampayan1998/Spring-Resume-Builder-Project/Logs/email-service
logging.file.name=${logging.file.path}/email-service.log
logging.logback.rollingpolicy.file-name-pattern=email-service-%d{yyyy-MM-dd}.%i.log
spring-email-and-file-upload=http://localhost:8020/uploadFile
spring-email-url=http://localhost:8020/scheduleEmail
app-url=https://localhost:6051/email
file.uploadDir=/home/aniketvaishampayan1998/Spring-Resume-Builder-Project/kwa_project/file-server
spring.jpa.hibernate.ddl-auto = none