email-template-variable=[\
{'customerName': 'CUSTOMERNAME'},\
{'customerContactNumber': 'CUSTOMERCONTACTNUMBER'},\
{'customerEmail':'CUSTOMEREMAIL'},\
{'customerBilingAmount':'CUSTOMERBILINGAMOUNT'},\
{'customerBillingDate':'CUSTOMERBILINGDATE'},\
{'customerAddressType':'CUSTOMERADDRESSTYPE'},\
{'customerTemporaryPassword':'CUSTOMERTEMPORARYPASSWORD'},\
{'forgetPasswordUrl':'FORGETPASSWORDURL'},\
{'requestNumber': 'REQUESTNUMBER'},\
{'accountNumber': 'ACCOUNTNUMBER'},\
{'requestCallType': 'REQUESTCALLTYPE'},\
{'billingAccount': 'BILLINGACCOUNT'},\
{'redirectUrl': 'REDIRECTURL'},\
{'date': 'DATE'},\
{'text': 'TEXT'}\
]




