
server.port=${SERVER_PORT:8020}

# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:192.168.1.16}:${POSTGRES_PORT:5432}/${POSTGRES_DB:crm_dev}?currentSchema=${SCHEMA_1:email}
spring.datasource.username=${POSTGRES_USER:crm_dev}
spring.datasource.password=${POSTGRES_PASSWORD:crm_dev@123}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.jta.atomikos.datasource.max-pool-size=15

spring.main.allow-bean-definition-overriding=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default-schema=email

## QuartzProperties
spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

## MailProperties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=avisyscrm@gmail.com
spring.mail.password=otlmltllctgcmuko
#ghhqsdtyhfrghgiz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app-url-email=${APP_URL_EMAIL:http://192.168.1.16:8000/email}

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
#spring.servlet.multipart.file-size-threshold=5MB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.uploadDir=${FILE_UPLOAD_URL_EMAIL:/home/avisyscrm/crm_project/Files/Development}


spring.application.name=email-service

#eureka.client.serviceUrl.defaultZone=http://192.168.1.16:8090/eureka
eureka.instance.hostname=${HOST_IP:192.168.1.16}
eureka.instance.preferIpAddress=true
eureka.instance.ipAddress=${spring.cloud.client.ip-address}
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
eureka.instance.statusPageUrl=http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/info
eureka.instance.healthCheckUrl=http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/health
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://192.168.1.16:8090/eureka}
eureka.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0


#logging.file.path=/var/log/spring-service
logging.file.path=${LOGGING_FILE_PATH:/home/avisyscrm/Logs/email-service}
logging.file.name=${logging.file.path}/email-service.log
logging.logback.rollingpolicy.file-name-pattern=email-service-%d{yyyy-MM-dd}.%i.log