server.port=${EMAIL_FILE_PORT}
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=email
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jta.atomikos.datasource.max-pool-size=15
spring.main.allow-bean-definition-overriding=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default-schema=email
spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app-url-email=https://localhost:6051/email
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
file.uploadDir=/home/aniketvaishampayan1998/Spring-Resume-Builder-Project/kwa_project/file-server
spring.application.name=EMAIL_FILE_SERVICE
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
eureka.enableSelfPreservation=false
spring.sleuth.sampler.probability=1.0
logging.file.path=/home/aniketvaishampayan1998/Spring-Resume-Builder-Project/Logs/email-file-service
logging.file.name=${logging.file.path}/email-file-service.log
logging.logback.rollingpolicy.file-name-pattern=email-service-%d{yyyy-MM-dd}.%i.log