#org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
### QuartzProperties
#spring.quartz.job-store-type=jdbc
#spring.quartz.jdbc.schema=classpath:org/quartz/impl/jdbcjobstore/tables_postgres.sql
#spring.quartz.properties.org.quartz.threadPool.threadCount=5
#
#org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
#org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#org.quartz.jobStore.useProperties=true
#org.quartz.jobStore.misfireThreshold=60000
#org.quartz.jobStore.tablePrefix=QRTZ_YOG_
#
#org.quartz.jobStore.dataSource=myDS
##org.quartz.jobListener.NAME.class=org.quartz.core.QuartzScheduler
#org.quartz.dataSource.myDS.driver=org.postgresql.Driver
#org.quartz.dataSource.myDS.URL=jdbc:postgresql://114.143.224.42:5432/crm_dev
#org.quartz.dataSource.myDS.user=crm_dev
#org.quartz.dataSource.myDS.password=crm_dev@123
#org.quartz.dataSource.myDS.maxConnections=30